CREATE TABLE MATERIALES(
	IdMaterial INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	Nombre VARCHAR(50) NOT NULL,
	Capacidad INT NOT NULL,
	Cantidad INT NOT NULL,
	Marca VARCHAR(50) NOT NULL,
	IdUnidad INT NOT NULL,
	CONSTRAINT fk_unidades_materiales FOREIGN KEY (IdUnidad) REFERENCES UNIDADES (IdUnidad)
);
