CREATE TABLE MOBILIARIO(
	IdMobiliario INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	Nombre VARCHAR(50) NOT NULL,
	Cantidad INT NOT NULL,
	Descripcion VARCHAR(200) NOT NULL,
	Material VARCHAR(50) NOT NULL
);